### ISSUE TITLE
Add a contact popup to facepile

### ISSUE THREAD

**Issue by swmoore84** [uxpin-merge/fluent-ui-uxpin-merge#36]
https://youtu.be/QvPjcukG2u4?t=1425

Anthony has requested for a popup to be added to the facepile component. 
This would popup when hovering over the avatars.

The popup should include the avatar, user information, and some buttons for actions such as email

<img width="194" alt="Screen Shot 2021-08-02 at 15 32 52" src="https://user-images.githubusercontent.com/54520519/127814415-01a9a9bf-6896-44a7-8022-a518506adbca.png">

**Comment by ahand** [comment]
Completed.
